---
name: AFLPlusPlus run test

on:
    schedule:
        - cron: "0 10 * * *"
    push:
        branches:
        - "**"

jobs:
    fuzzing_job:
        runs-on: ubuntu-latest
        name: AFL++ Fuzzing
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v2
            
            - name: Build with AFL++
              uses: ./aflplusplus_build
              with:
                source_dir: "./demo_project"
                compiler: "clang-lto"
                use_asan: true

            - name: Create Input Folder
              run: mkdir -p ./build/test/input
            
            - name: Create Input File
              run: echo "Input data" > ./build/test/input/input.txt

            - name: Run AFL++ Fuzzing Action
              uses: ./aflplusplus_run
              with:
                campaign_name: "Test Campaign"
                fuzz_target: "./build/test"
                input_folder: "./build/test/input"
                timeout: 10
                time: 120
                qemu_mode: false
                