---
name: AFLPlusPlus run test

on:
    push:
        branches:
        - "**"

jobs:
    fuzzing_job:
        runs-on: ubuntu-latest
        name: AFL++ Fuzzing
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v2
            
            - name: AFL++ fuzz test build action
              id: build
              uses: g0ku704/aflplusplus_build_action@v1.0.0 
              with:
                file_name: "test"
                source: "./demo_project"
                compiler: "clang-lto"
                use_asan: true

            - name: Echo Binary Path
              run: |
                echo "Binary Path: ${{ steps.build.outputs.binary_path }}"

            - name: Create Input/Output Folders
              run: |
                mkdir -p ./input
                mkdir -p ./output
            
            - name: Create Input File
              run: echo "Input data" > ./input/input.txt

            - name: AFL++ fuzzing action 
              id: run
              uses: g0ku704/aflplusplus_fuzz_action@v1.0.0
              with:
                campaign_name: "TestCampaign" # no spaces allowed
                fuzz_target: "${{ steps.build.outputs.binary_path }}"
                input_folder: "./input"
                output_folder: "./output"
                timeout: 10
                time: 120
                qemu_mode: false
                
